### ISSUE TITLE
Parameter error

### ISSUE THREAD

**Issue by JackPo** [dnewsholme/GoogleDynamicDNS#1]
Invoke-RestMethod : A parameter cannot be found that matches parameter name 'Authentication'.
At D:\GDRIVE\Scripts\GoogleDynamicDNS-master\Functions\Update-GoogleDynamicDNS.ps1:25 char:17
+                 -Authentication Basic `
+                 ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-RestMethod], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by dnewsholme** [comment]
The parameter authentication is only available within powershell 6.0+ you need to install powershell core.

https://github.com/PowerShell/PowerShell
