### ISSUE TITLE
PowerShell 7 Error

### ISSUE THREAD

**Issue by tapr00t** [dnewsholme/GoogleDynamicDNS#4]
I get the following error when trying to run, using windows 10 with powershell 7:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "-e": executable file not found in $PATH: unknown.

**Comment by dnewsholme** [comment]
I take it you are using via the docker run command rather than using docker compose?

Are you using the run command as shown in the readme?

**Comment by tapr00t** [comment]
Thanks for the reply!
Correct, I'm using the commands as provided in the readme.
I do have docker compose which I'm using to run something else, but I'm pretty new to docker and not exactly sure how to get it working with GoogleDynamicDNS.
The other program has its own folder under my user folder with a docker-compose.yml there.
But I'm not sure where the folder is on disk for GoogleDynamicDNS, which I assume is where I would put its docker compose file.

**Comment by dnewsholme** [comment]
Sorry looking at it, it appears my readme had the wrong syntax. The container name should go at the end of the run command so it should be.

```bash
sudo docker run -e GDNS_USERNAME="jhksoo" -e GDNS_PASSWORD="sokoks" -e GDNS_DOMAINRECORD="dev.website.com" -e GDNS_FREQUENCY="300" dnewsholme/googledynamicdns
```

Or if you prefer to use docker compose you can place your docker-compose.yml file anywhere you like on your machine then navigate into that folder in the shell and run `sudo docker-compose up -d` to run the container as a daemon.

I'll update the readme to fix the mistake. Let me know if you do/don't manage to get it working.

**Comment by tapr00t** [comment]
Thanks for the help!  I got it running via docker-compose, but the ddns did not update, is there an error log I can view somewhere?

**Comment by dnewsholme** [comment]
It will log out to the console which you can view via the docker logging mechanism.

You can view the logs by running `sudo docker-compose logs` from the location of your docker-compose.yml

**Comment by tapr00t** [comment]
I got this log output:
![image](https://user-images.githubusercontent.com/3802245/111169262-2c8e6a80-8579-11eb-843b-23b221ee5a9c.png)

Google DDNS Info:
![image](https://user-images.githubusercontent.com/3802245/111169011-fa7d0880-8578-11eb-8fe7-a3e9c0827903.png)

docker-compose.yml:
![image](https://user-images.githubusercontent.com/3802245/111169175-1aacc780-8579-11eb-8647-7c22b69bd880.png)

Maybe I'm specifying the "domain record" incorrectly?

**Comment by dnewsholme** [comment]
I take it you are wanting to update the root record? You just need to specifiy the fqdn without the `@.` so for example google.com would just be google.com rather than @.google.com.

Hope that makes sense?

**Comment by tapr00t** [comment]
Makes sense, but I removed the @. from my config, shutdown and started up the docker service, and getting the same error again:
![image](https://user-images.githubusercontent.com/3802245/111171206-171a4000-857b-11eb-9a2f-5657ca35d64b.png)

I found I can use a web address (https://webmasters.stackexchange.com/questions/76739/what-is-the-update-url-for-dynamic-dns-for-google-domains) to update the DDNS and can automate that, if you don't want to debug this anymore.  But if you wish to keep debugging I'll can try anything else you think might help figure this out.  Otherwise feel free to close this issue.

Oh and when I did the URL update, it did use the "@." and it had updated it.
![image](https://user-images.githubusercontent.com/3802245/111172063-e1c22200-857b-11eb-97ec-828f01fb042a.png)

**Comment by dnewsholme** [comment]
Try taking the container down and bringing it back up again.

` sudo docker-compose down`

Then bringing back up.

`sudo docker-compose up`

It does work with the domain name how i said.

**Comment by tapr00t** [comment]
That is what I had done.
![image](https://user-images.githubusercontent.com/3802245/111174138-93ae1e00-857d-11eb-92e7-09f745cb71fd.png)

**Comment by dnewsholme** [comment]
Strange it definitely does work how i said.

![gdns](https://user-images.githubusercontent.com/5154065/111176872-9f134080-85a1-11eb-9969-5ca790dda209.PNG)
Ignore the slightly different syntax of my variable to your docker-compose file as i'm running it via kubernetes.
Entering only my root domain name of dnewsholme.co.uk does update my @ record.

![domains](https://user-images.githubusercontent.com/5154065/111176948-b18d7a00-85a1-11eb-8ef0-dd4eb2adc007.PNG)

However I've made some changes to the code to urlencode the domain record i think what was happening before is the @ on the domain wasn't properly encoded therefore failed to update.

The docker image has been updated on dockerhub. Try pulling the latest image `sudo docker pull dnewsholme/googledynamicdns:latest`

This should allow you to update via the @.taproot.net format.
![pwsh](https://user-images.githubusercontent.com/5154065/111176791-8c990700-85a1-11eb-8e15-3dab3264a103.PNG)

**Comment by tapr00t** [comment]
Are you sure yours is updating?  Your image shows last update in September

**Comment by dnewsholme** [comment]
100% sure yeah i've been running it for years. September was just the date my ISP last changed my external IP so since then it's not updated since there has been no change.

The logs confirm this with the nochg output.

![Capture](https://user-images.githubusercontent.com/5154065/111182492-dc2e0180-85a6-11eb-97f8-691095285026.PNG)

**Comment by dnewsholme** [comment]
Closing issue as domain update is working.
